name: Building Rfam Tutorial Containers

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: docker build -f Dockerfile -t rfam/tutorials:latest .

      - name: docker push
        run: docker push rfam/tutorials:latest
